### ISSUE TITLE
LdapAuthService::checkCredentialsAgainstForwardAuth(): Return value must be of type array, Adldap\Models\User returned

### ISSUE THREAD

**Issue by alexc-jeromes** [Daynnnnn/statamic-forward-auth#4]
PHP 8.2.12

Adldap returns a User model, not an array.

LdapAuthService.php [60] - to fix, cast the model to array:

```php
finally {
            return (array)$this->forwardAuthUser;
        }
```

**Comment by Daynnnnn** [comment]
Sorry this took a while! About to push 5.0, which moves to LdapRecord
